version: '3.8'
 
services:
  server-clg:
    image: ${BACKEND_ECR_REGISTRY}/${BACKEND_ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: ${BACKEND_ECR_REGISTRY}
    ports:
      - "4002:4000"
    restart: unless-stopped
