name: Frontend Build & Deploy on Spot Runner

on:
  push:
    branches: [main]
    paths:
      - "client/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  start-runner:
    timeout-minutes: 5
    name: Start EC2 Spot Instance Runner
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write

    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-east-1"
          role-to-assume: arn:aws:iam::882027629355:role/github-actions-oidc-Role
          audience: sts.amazonaws.com
          output-credentials: true

      - name: Start EC2 Spot Runner
        id: start-ec2-runner
        uses: NextChapterSoftware/ec2-action-builder@v1.10
        with:
          github_token: ${{ secrets.GT_FINE_GRAINED_TOKEN }}
          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          aws_region: "us-east-1"
          ec2_subnet_id: "subnet-0526bdb1507c2592b"
          ec2_security_group_id: "sg-020dee825ad3c6447"
          ec2_instance_type: t3.medium
          ec2_ami_id: "ami-08a586751e916c870"
          ec2_instance_ttl: 30
          ec2_spot_instance_strategy: None
          ec2_instance_tags: >
            [
              {"Key": "Owner", "Value": "deploybot"}
            ]

  build-push-deploy:
    needs: start-runner
    runs-on: ${{ github.run_id }} # <-- Uses the same dynamically created runner
    env:
      FRONTEND_ECR_REGISTRY: ${{ secrets.FRONTEND_ECR_REGISTRY }}
      FRONTEND_ECR_REPOSITORY: ${{ secrets.FRONTEND_ECR_REPOSITORY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IMAGE_TAG: ${{ vars.FRONTEND_BUILD_NUMBER }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::882027629355:role/github-actions-oidc-Role
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Build and Push Frontend Image
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $FRONTEND_ECR_REGISTRY
          docker build -t $FRONTEND_ECR_REGISTRY/$FRONTEND_ECR_REPOSITORY:$(( $IMAGE_TAG + 1 )) client/
          docker push $FRONTEND_ECR_REGISTRY/$FRONTEND_ECR_REPOSITORY:$(( $IMAGE_TAG + 1 ))
          docker image prune -af

      - name: Increment FRONTEND_BUILD_NUMBER
        run: |
          GH_API_URL="https://api.github.com/repos/Varunpro16/Clg-leave-app/actions/variables/FRONTEND_BUILD_NUMBER"
          CURRENT_VALUE=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" -H "Accept: application/vnd.github+json" $GH_API_URL | jq -r '.value')
          NEW_VALUE=$((CURRENT_VALUE + 1))
          curl -X PATCH $GH_API_URL \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -d "{\"value\": \"$NEW_VALUE\" }"
          echo "Updated FRONTEND_BUILD_NUMBER to $NEW_VALUE"

      - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "client/docker-compose.yml"
          target: "~/frontend/"
          overwrite: true

      - name: Deploy Frontend to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.FRONTEND_DEPLOY_FOLDER }}/client
            export FRONTEND_ECR_REGISTRY=${{ secrets.FRONTEND_ECR_REGISTRY }}
            export FRONTEND_ECR_REPOSITORY=${{ secrets.FRONTEND_ECR_REPOSITORY }}
            FRONTEND_BUILD_NUMBER=${{ vars.FRONTEND_BUILD_NUMBER }}
            IMAGE_TAG=$(( FRONTEND_BUILD_NUMBER + 1 ))
            export IMAGE_TAG
            export AWS_REGION=${{ secrets.AWS_REGION }}

            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $FRONTEND_ECR_REGISTRY
            docker pull $FRONTEND_ECR_REGISTRY/$FRONTEND_ECR_REPOSITORY:$IMAGE_TAG
            docker-compose up -d
            docker image prune -f
